### ISSUE TITLE
Script for Downloading Submissions from URLs

### ISSUE THREAD

**Issue by jaredb1011** [waldo-vision/models#2]
### Description:
We need to develop or implement existing code that takes an input list of YouTube video URLs and downloads the videos to a specified directory. This will be run on a Linux system.

### Requirements:
Ability to input a list of YouTube video URLs (e.g., via a text file or command line arguments).
Validate input URLs to ensure they are valid YouTube video URLs.
Download each video in a specified format (e.g., MP4, WebM, etc.).
Save downloaded videos to a specified directory.
Provide progress updates during the download process (e.g., percentage completed, estimated time remaining, etc.).
Handle download errors, such as network issues or invalid URLs, gracefully.
Provide clear documentation on how to use the code and specify the download directory and format.

### Acceptance Criteria:
Successfully input a list of YouTube video URLs (e.g., via a text file or command line arguments).
Validate input URLs to ensure they are valid YouTube video URLs with at least 95% accuracy.
Download each video in the specified format (e.g., MP4, WebM, etc.).
Save downloaded videos to the specified directory.
Provide progress updates during the download process, including percentage completed and estimated time remaining.
Handle download errors, such as network issues or invalid URLs, gracefully, without crashing the program.
Clear documentation provided on how to use the code and specify the download directory and format.

### Notes:
For better compatibility and to comply with YouTube's terms of service, consider using open-source libraries and tools specifically designed for this purpose, such as youtube-dl, pytube, or similar.
This issue is partially blocked by #1 because we don't know yet the format in which links will be stored locally.

**Comment by Bensikrac** [comment]
May I suggest youtube-dl as tool, since it is practically made for youtube, but it also supports a lot more plattforms if needed in the future
here is a sample command: 
youtube-dl --batch-file _INSERT FILE WITH 1 video link per line here_ --output _HERE Filename formatting_ --format 'bestvideo[ext=mp4]/bestvideo' --ignore-errors --no-continue --no-part --recode-video mp4 --ffmpeg-location _FFMPEG_PATH_HERE_

this may throw captcha errors, which can also be handled if needed.(Proxies can be used, or using rate limiting with further options is possible). 
Also if format is wrong, you can reencode to mp4 with ffmpeg. 
Instead of the long file list, you can read the urls from stdin aswell, and therefore could pipe it into youtube-dl like so:
(database command) | youtube-dl --batch-file - _Other options like above_
The output directory can be set with filename formatting, either absolute or relative
if videos are not in mp4, they are automatically reencoded into mp4 with ffmpeg

**Comment by Bensikrac** [comment]
and what does the server run on? Linux/Windows, does it have bash / cmd. Does it have the ability to install dependencies like ffmpeg / youtube-dl. Or should this be a docker container?

**Comment by jaredb1011** [comment]
@Bensikrac I've updated the issue description to incorporate some of your comments
